### PR TITLE
Fix PUBLIC_URI bugs

### LINKED ISSUE #163: Process exits if PUBLIC_URI environment variable is not available
If the `PUBLIC_URI` is not available in the process environment the server should default to localhost + port. Currently the process exits if it is not set

### PR DESCRIPTION
**Pull request by evert**
* Better grammar
* Now correctly uses the default
* Added a ⚾

Fixes #163

### CODE REVIEW

File: src/app.ts [hunk 1]
```diff
@@ -7,10 +7,17 @@ import accessLog from '@curveball/accesslog';
 
 import { load } from './server-settings';
 
+const pkgInfo = require('../package.json');
+console.log('⚾ Curveball %s %s', pkgInfo.name, pkgInfo.version);
```
Comment (merrickread) [inline src/app.ts]: very hip

Comment (merrickread) [reply src/app.ts]: ready for the big leagues

Comment (evert) [reply src/app.ts]: <3
