### PR TITLE
User inactive fixes

### LINKED ISSUE #69: Throw a better error message when a user tries to log in but their account is not yet active.

### PR DESCRIPTION
**Pull request by juhangsin**
#69

### CODE REVIEW

File: src/user/service.ts [hunk 1]
```diff
@@ -39,7 +40,7 @@ export async function findById(id: number): Promise<User> {
 }
 export async function findByIdentity(identity: string): Promise<User> {
```
Comment (merrickread) [inline src/user/service.ts]: With this function and `findAll()` above, it's generally best to pass the entire user object as a parameter since you can guarantee the typeset. I can show you examples in the media-api another day. 

Doesn't have to change for this PR, but something to keep in mind going forward.

File: src/user/types.ts [hunk 2]
```diff
@@ -8,6 +8,7 @@ export type NewUser = {
   nickname: string,
   created: Date,
   type: UserType,
+  active: boolean
 };
```
Comment (merrickread) [inline src/user/types.ts]: Also a nice way to declare the NewUser type is something like this:

`export type NewUser = Omit<User, 'id'>;`

It's the same type as the user, except you don't have an id yet. The id can be appended to the record once the record is inserted into the db.
